export const FETCH_TASK_COUNTS = 'FETCH_TASK_COUNTS';
export const FETCH_TASK_COUNTS_SUCCESS = 'FETCH_TASK_COUNTS_SUCCESS';
export const FETCH_TASK_COUNTS_FAILURE = 'FETCH_TASK_COUNT_FAILURE';


export const FETCH_NOTIFICATIONS_COUNT = 'FETCH_NOTIFICATIONS_COUNT';
export const FETCH_NOTIFICATIONS_COUNT_SUCCESS = 'FETCH_NOTIFICATIONS_COUNT_SUCCESS';
export const FETCH_NOTIFICATIONS_COUNT_FAILURE = 'FETCH_NOTIFICATIONS_COUNT_FAILURE';


export const SET_DEFAULT_COUNTS = 'SET_DEFAULT_COUNTS';
