export const FETCH_ACTIVE_SHIFT = 'FETCH_ACTIVE_SHIFT';
export const FETCH_ACTIVE_SHIFT_SUCCESS = 'FETCH_ACTIVE_SHIFT_SUCCESS';
export const FETCH_ACTIVE_SHIFT_FAILURE = 'FETCH_ACTIVE_SHIFT_FAILURE';

export const CREATE_ACTIVE_SHIFT = 'CREATE_ACTIVE_SHIFT';
export const CREATE_ACTIVE_SHIFT_SUCCESS = 'CREATE_ACTIVE_SHIFT_SUCCESS';
export const CREATE_ACTIVE_SHIFT_FAILURE = 'CREATE_ACTIVE_SHIFT_FAILURE';

export const SUBMIT_VALIDATION = 'SUBMIT_VALIDATION';
export const SUBMIT_VALIDATION_SUCCESS = 'SUBMIT_VALIDATION_SUCCESS';
export const SUBMIT_VALIDATION_FAILURE = 'SUBMIT_VALIDATION_FAILURE';

export const FETCH_ACTIVE_SHIFT_AFTER_CREATE = 'FETCH_ACTIVE_SHIFT_AFTER_CREATE';

export const FETCH_SHIFT_FORM = 'FETCH_SHIFT_FORM';
export const FETCH_SHIFT_FORM_SUCCESS = 'FETCH_SHIFT_FORM_SUCCESS';
export const FETCH_SHIFT_FORM_FAILURE = 'FETCH_SHIFT_FORM_FAILURE';


export const FETCH_STAFF_DETAILS = 'FETCH_STAFF_DETAILS';
export const FETCH_STAFF_DETAILS_SUCCESS = 'FETCH_STAFF_DETAILS_SUCCESS';
export const FETCH_STAFF_DETAILS_FAILURE = 'FETCH_STAFF_DETAILS_FAILURE';


export const END_SHIFT = 'END_SHIFT';
export const END_SHIFT_SUCCESS = 'END_SHIFT_SUCCESS';
export const END_SHIFT_FAILURE = 'END_SHIFT_FAILURE';

export const SET_HAS_ACTIVE_SHIFT = 'SET_HAS_ACTIVE_SHIFT';


export const PERFORM_ONBOARDING_CHECK = 'PERFORM_ONBOARDING_CHECK';
export const PERFORM_ONBOARDING_CHECK_COMPLETE = 'PERFORM_ONBOARDING_CHECK_COMPLETE';
