/* eslint-disable import/prefer-default-export */
export const countries = [
  {
    Identifier: 2,
    alphaCode: 'AFG',
    countryName: 'Afghanistan',
    dialCode: '93',
  },
  {
    Identifier: 249,
    alphaCode: 'ALA',
    countryName: 'Aland Islands',
    dialCode: '358',
  },
  {
    Identifier: 3,
    alphaCode: 'ALB',
    countryName: 'Albania',
    dialCode: '355',
  },
  {
    Identifier: 4,
    alphaCode: 'DZA',
    countryName: 'Algeria',
    dialCode: '213',
  },
  {
    Identifier: 5,
    alphaCode: 'ASM',
    countryName: 'American Samoa',
    dialCode: '1-684',
  },
  {
    Identifier: 6,
    alphaCode: 'AND',
    countryName: 'Andorra',
    dialCode: '376',
  },
  {
    Identifier: 7,
    alphaCode: 'AGO',
    countryName: 'Angola',
    dialCode: '244',
  },
  {
    Identifier: 8,
    alphaCode: 'AIA',
    countryName: 'Anguilla',
    dialCode: '1-264',
  },
  {
    Identifier: 9,
    alphaCode: 'ATA',
    countryName: 'Antarctica',
    dialCode: '672',
  },
  {
    Identifier: 10,
    alphaCode: 'ATG',
    countryName: 'Antigua and Barbuda',
    dialCode: '1-268',
  },
  {
    Identifier: 11,
    alphaCode: 'ARG',
    countryName: 'Argentina',
    dialCode: '54',
  },
  {
    Identifier: 12,
    alphaCode: 'ARM',
    countryName: 'Armenia',
    dialCode: '374',
  },
  {
    Identifier: 13,
    alphaCode: 'ABW',
    countryName: 'Aruba',
    dialCode: '297',
  },
  {
    Identifier: 14,
    alphaCode: 'AUS',
    countryName: 'Australia',
    dialCode: '61',
  },
  {
    Identifier: 15,
    alphaCode: 'AUT',
    countryName: 'Austria',
    dialCode: '43',
  },
  {
    Identifier: 16,
    alphaCode: 'AZE',
    countryName: 'Azerbaijan',
    dialCode: '994',
  },
  {
    Identifier: 17,
    alphaCode: 'BHS',
    countryName: 'Bahamas (the)',
    dialCode: '1-242',
  },
  {
    Identifier: 18,
    alphaCode: 'BHR',
    countryName: 'Bahrain',
    dialCode: '973',
  },
  {
    Identifier: 19,
    alphaCode: 'BGD',
    countryName: 'Bangladesh',
    dialCode: '880',
  },
  {
    Identifier: 20,
    alphaCode: 'BRB',
    countryName: 'Barbados',
    dialCode: '1-246',
  },
  {
    Identifier: 21,
    alphaCode: 'BLR',
    countryName: 'Belarus',
    dialCode: '375',
  },
  {
    Identifier: 22,
    alphaCode: 'BEL',
    countryName: 'Belgium',
    dialCode: '32',
  },
  {
    Identifier: 23,
    alphaCode: 'BLZ',
    countryName: 'Belize',
    dialCode: '501',
  },
  {
    Identifier: 24,
    alphaCode: 'BEN',
    countryName: 'Benin',
    dialCode: '229',
  },
  {
    Identifier: 25,
    alphaCode: 'BMU',
    countryName: 'Bermuda',
    dialCode: '1-441',
  },
  {
    Identifier: 26,
    alphaCode: 'BTN',
    countryName: 'Bhutan',
    dialCode: '975',
  },
  {
    Identifier: 27,
    alphaCode: 'BOL',
    countryName: 'Bolivia (Plurinational State Of)',
    dialCode: '591',
  },
  {
    Identifier: 28,
    alphaCode: 'BES',
    countryName: 'Bonaire Sint Eustatius and Saba',
    dialCode: '599',
  },
  {
    Identifier: 29,
    alphaCode: 'BIH',
    countryName: 'Bosnia and Herzegovina',
    dialCode: '387',
  },
  {
    Identifier: 30,
    alphaCode: 'BWA',
    countryName: 'Botswana',
    dialCode: '267',
  },
  {
    Identifier: 31,
    alphaCode: 'BVT',
    countryName: 'Bouvet Island',
    dialCode: '47',
  },
  {
    Identifier: 32,
    alphaCode: 'BRA',
    countryName: 'Brazil',
    dialCode: '55',
  },
  {
    Identifier: 33,
    alphaCode: 'IOT',
    countryName: 'British Indian Ocean Territory (the)',
    dialCode: '246',
  },
  {
    Identifier: 35,
    alphaCode: 'BRN',
    countryName: 'Brunei Darussalam',
    dialCode: '673',
  },
  {
    Identifier: 36,
    alphaCode: 'BGR',
    countryName: 'Bulgaria',
    dialCode: '359',
  },
  {
    Identifier: 37,
    alphaCode: 'BFA',
    countryName: 'Burkina Faso',
    dialCode: '226',
  },
  {
    Identifier: 151,
    alphaCode: 'MMR',
    countryName: 'Burma',
    dialCode: '95',
  },
  {
    Identifier: 38,
    alphaCode: 'BDI',
    countryName: 'Burundi',
    dialCode: '257',
  },
  {
    Identifier: 40,
    alphaCode: 'KHM',
    countryName: 'Cambodia',
    dialCode: '855',
  },
  {
    Identifier: 41,
    alphaCode: 'CMR',
    countryName: 'Cameroon',
    dialCode: '237',
  },
  {
    Identifier: 42,
    alphaCode: 'CAN',
    countryName: 'Canada',
    dialCode: '1',
  },
  {
    Identifier: 39,
    alphaCode: 'CPV',
    countryName: 'Cape Verde',
    dialCode: '238',
  },
  {
    Identifier: 43,
    alphaCode: 'CYM',
    countryName: 'Cayman Islands (the)',
    dialCode: '1-345',
  },
  {
    Identifier: 44,
    alphaCode: 'CAF',
    countryName: 'Central African Republic (the)',
    dialCode: '236',
  },
  {
    Identifier: 45,
    alphaCode: 'TCD',
    countryName: 'Chad',
    dialCode: '235',
  },
  {
    Identifier: 46,
    alphaCode: 'CHL',
    countryName: 'Chile',
    dialCode: '56',
  },
  {
    Identifier: 47,
    alphaCode: 'CHN',
    countryName: 'China',
    dialCode: '86',
  },
  {
    Identifier: 50,
    alphaCode: 'CXR',
    countryName: 'Christmas Island',
    dialCode: '61',
  },
  {
    Identifier: 51,
    alphaCode: 'CCK',
    countryName: 'Cocos (Keeling) Islands (the)',
    dialCode: '61',
  },
  {
    Identifier: 52,
    alphaCode: 'COL',
    countryName: 'Colombia',
    dialCode: '57',
  },
  {
    Identifier: 53,
    alphaCode: 'COM',
    countryName: 'Comoros (the)',
    dialCode: '269',
  },
  {
    Identifier: 64,
    alphaCode: 'COD',
    countryName: 'Congo (the Democratic Republic of the)',
    dialCode: '243',
  },
  {
    Identifier: 54,
    alphaCode: 'COG',
    countryName: 'Congo (the)',
    dialCode: '242',
  },
  {
    Identifier: 55,
    alphaCode: 'COK',
    countryName: 'Cook Islands (the)',
    dialCode: '682',
  },
  {
    Identifier: 56,
    alphaCode: 'CRI',
    countryName: 'Costa Rica',
    dialCode: '506',
  },
  {
    Identifier: 57,
    alphaCode: 'HRV',
    countryName: 'Croatia',
    dialCode: '385',
  },
  {
    Identifier: 58,
    alphaCode: 'CUB',
    countryName: 'Cuba',
    dialCode: '53',
  },
  {
    Identifier: 59,
    alphaCode: 'CUW',
    countryName: 'Curacao',
    dialCode: '599',
  },
  {
    Identifier: 60,
    alphaCode: 'CYP',
    countryName: 'Cyprus',
    dialCode: '357',
  },
  {
    Identifier: 61,
    alphaCode: 'CZE',
    countryName: 'Czechia',
    dialCode: '420',
  },
  {
    Identifier: 65,
    alphaCode: 'DNK',
    countryName: 'Denmark',
    dialCode: '45',
  },
  {
    Identifier: 66,
    alphaCode: 'DJI',
    countryName: 'Djibouti',
    dialCode: '253',
  },
  {
    Identifier: 67,
    alphaCode: 'DMA',
    countryName: 'Dominica',
    dialCode: '1-767',
  },
  {
    Identifier: 68,
    alphaCode: 'DOM',
    countryName: 'Dominican Republic (the)',
    dialCode: '1-809,1-829,1-849',
  },
  {
    Identifier: 221,
    alphaCode: 'TLS',
    countryName: 'East Timor',
    dialCode: '670',
  },
  {
    Identifier: 69,
    alphaCode: 'ECU',
    countryName: 'Ecuador',
    dialCode: '593',
  },
  {
    Identifier: 70,
    alphaCode: 'EGY',
    countryName: 'Egypt',
    dialCode: '20',
  },
  {
    Identifier: 71,
    alphaCode: 'SLV',
    countryName: 'El Salvador',
    dialCode: '503',
  },
  {
    Identifier: 72,
    alphaCode: 'GNQ',
    countryName: 'Equatorial Guinea',
    dialCode: '240',
  },
  {
    Identifier: 73,
    alphaCode: 'ERI',
    countryName: 'Eritrea',
    dialCode: '291',
  },
  {
    Identifier: 74,
    alphaCode: 'EST',
    countryName: 'Estonia',
    dialCode: '372',
  },
  {
    Identifier: 214,
    alphaCode: 'SWZ',
    countryName: 'Eswatini',
    dialCode: '268',
  },
  {
    Identifier: 75,
    alphaCode: 'ETH',
    countryName: 'Ethiopia',
    dialCode: '251',
  },
  {
    Identifier: 76,
    alphaCode: 'FLK',
    countryName: 'Falkland Islands (the)',
    dialCode: '500',
  },
  {
    Identifier: 77,
    alphaCode: 'FRO',
    countryName: 'Faroe Islands (the)',
    dialCode: '298',
  },
  {
    Identifier: 78,
    alphaCode: 'FJI',
    countryName: 'Fiji',
    dialCode: '679',
  },
  {
    Identifier: 79,
    alphaCode: 'FIN',
    countryName: 'Finland',
    dialCode: '358',
  },
  {
    Identifier: 80,
    alphaCode: 'FRA',
    countryName: 'France (European territory)',
    dialCode: '33',
  },
  {
    Identifier: 81,
    alphaCode: 'GUF',
    countryName: 'French Guiana',
    dialCode: '594',
  },
  {
    Identifier: 82,
    alphaCode: 'PYF',
    countryName: 'French Polynesia',
    dialCode: '689',
  },
  {
    Identifier: 83,
    alphaCode: 'ATF',
    countryName: 'French Southern Territories (the)',
    dialCode: '262',
  },
  {
    Identifier: 84,
    alphaCode: 'GAB',
    countryName: 'Gabon',
    dialCode: '241',
  },
  {
    Identifier: 85,
    alphaCode: 'GMB',
    countryName: 'Gambia (the)',
    dialCode: '220',
  },
  {
    Identifier: 86,
    alphaCode: 'GEO',
    countryName: 'Georgia',
    dialCode: '995',
  },
  {
    Identifier: 87,
    alphaCode: 'DEU',
    countryName: 'Germany',
    dialCode: '49',
  },
  {
    Identifier: 88,
    alphaCode: 'GHA',
    countryName: 'Ghana',
    dialCode: '233',
  },
  {
    Identifier: 89,
    alphaCode: 'GIB',
    countryName: 'Gibraltar',
    dialCode: '350',
  },
  {
    Identifier: 90,
    alphaCode: 'GRC',
    countryName: 'Greece',
    dialCode: '30',
  },
  {
    Identifier: 91,
    alphaCode: 'GRL',
    countryName: 'Greenland',
    dialCode: '299',
  },
  {
    Identifier: 92,
    alphaCode: 'GRD',
    countryName: 'Grenada',
    dialCode: '1-473',
  },
  {
    Identifier: 93,
    alphaCode: 'GLP',
    countryName: 'Guadeloupe',
    dialCode: '590',
  },
  {
    Identifier: 94,
    alphaCode: 'GUM',
    countryName: 'Guam',
    dialCode: '1-671',
  },
  {
    Identifier: 95,
    alphaCode: 'GTM',
    countryName: 'Guatemala',
    dialCode: '502',
  },
  {
    Identifier: 96,
    alphaCode: 'GGY',
    countryName: 'Guernsey',
    dialCode: '44',
  },
  {
    Identifier: 97,
    alphaCode: 'GIN',
    countryName: 'Guinea',
    dialCode: '224',
  },
  {
    Identifier: 98,
    alphaCode: 'GNB',
    countryName: 'Guinea-Bissau',
    dialCode: '245',
  },
  {
    Identifier: 99,
    alphaCode: 'GUY',
    countryName: 'Guyana',
    dialCode: '592',
  },
  {
    Identifier: 100,
    alphaCode: 'HTI',
    countryName: 'Haiti',
    dialCode: '509',
  },
  {
    Identifier: 101,
    alphaCode: 'HMD',
    countryName: 'Heard Island and McDonald Islands',
    dialCode: '672',
  },
  {
    Identifier: 103,
    alphaCode: 'HND',
    countryName: 'Honduras',
    dialCode: '504',
  },
  {
    Identifier: 48,
    alphaCode: 'HKG',
    countryName: 'Hong Kong',
    dialCode: '852',
  },
  {
    Identifier: 104,
    alphaCode: 'HUN',
    countryName: 'Hungary',
    dialCode: '36',
  },
  {
    Identifier: 105,
    alphaCode: 'ISL',
    countryName: 'Iceland',
    dialCode: '354',
  },
  {
    Identifier: 106,
    alphaCode: 'IND',
    countryName: 'India',
    dialCode: '91',
  },
  {
    Identifier: 107,
    alphaCode: 'IDN',
    countryName: 'Indonesia',
    dialCode: '62',
  },
  {
    Identifier: 250,
    alphaCode: 'XZZ',
    countryName: 'International Waters',
    dialCode: '0',
  },
  {
    Identifier: 108,
    alphaCode: 'IRN',
    countryName: 'Iran (Islamic Republic of)',
    dialCode: '98',
  },
  {
    Identifier: 109,
    alphaCode: 'IRQ',
    countryName: 'Iraq',
    dialCode: '964',
  },
  {
    Identifier: 110,
    alphaCode: 'IRL',
    countryName: 'Ireland',
    dialCode: '353',
  },
  {
    Identifier: 111,
    alphaCode: 'IMN',
    countryName: 'Isle of Man',
    dialCode: '44',
  },
  {
    Identifier: 112,
    alphaCode: 'ISR',
    countryName: 'Israel',
    dialCode: '972',
  },
  {
    Identifier: 113,
    alphaCode: 'ITA',
    countryName: 'Italy',
    dialCode: '39',
  },
  {
    Identifier: 62,
    alphaCode: 'CIV',
    countryName: 'Ivory Coast',
    dialCode: '225',
  },
  {
    Identifier: 114,
    alphaCode: 'JAM',
    countryName: 'Jamaica',
    dialCode: '1-876',
  },
  {
    Identifier: 115,
    alphaCode: 'JPN',
    countryName: 'Japan',
    dialCode: '81',
  },
  {
    Identifier: 116,
    alphaCode: 'JEY',
    countryName: 'Jersey',
    dialCode: '44',
  },
  {
    Identifier: 117,
    alphaCode: 'JOR',
    countryName: 'Jordan',
    dialCode: '962',
  },
  {
    Identifier: 118,
    alphaCode: 'KAZ',
    countryName: 'Kazakhstan',
    dialCode: '7',
  },
  {
    Identifier: 119,
    alphaCode: 'KEN',
    countryName: 'Kenya',
    dialCode: '254',
  },
  {
    Identifier: 120,
    alphaCode: 'KIR',
    countryName: 'Kiribati',
    dialCode: '686',
  },
  {
    Identifier: 63,
    alphaCode: 'PRK',
    countryName: 'Korea (North)',
    dialCode: '850',
  },
  {
    Identifier: 178,
    alphaCode: 'KOR',
    countryName: 'Korea (South)',
    dialCode: '82',
  },
  {
    Identifier: 251,
    alphaCode: 'RKS',
    countryName: 'Kosovo',
    dialCode: '383',
  },
  {
    Identifier: 121,
    alphaCode: 'KWT',
    countryName: 'Kuwait',
    dialCode: '965',
  },
  {
    Identifier: 122,
    alphaCode: 'KGZ',
    countryName: 'Kyrgyzstan',
    dialCode: '996',
  },
  {
    Identifier: 123,
    alphaCode: 'LAO',
    countryName: 'Laos',
    dialCode: '856',
  },
  {
    Identifier: 124,
    alphaCode: 'LVA',
    countryName: 'Latvia',
    dialCode: '371',
  },
  {
    Identifier: 125,
    alphaCode: 'LBN',
    countryName: 'Lebanon',
    dialCode: '961',
  },
  {
    Identifier: 126,
    alphaCode: 'LSO',
    countryName: 'Lesotho',
    dialCode: '266',
  },
  {
    Identifier: 127,
    alphaCode: 'LBR',
    countryName: 'Liberia',
    dialCode: '231',
  },
  {
    Identifier: 128,
    alphaCode: 'LBY',
    countryName: 'Libya',
    dialCode: '218',
  },
  {
    Identifier: 129,
    alphaCode: 'LIE',
    countryName: 'Liechtenstein',
    dialCode: '423',
  },
  {
    Identifier: 130,
    alphaCode: 'LTU',
    countryName: 'Lithuania',
    dialCode: '370',
  },
  {
    Identifier: 131,
    alphaCode: 'LUX',
    countryName: 'Luxembourg',
    dialCode: '352',
  },
  {
    Identifier: 49,
    alphaCode: 'MAC',
    countryName: 'Macao',
    dialCode: '853',
  },
  {
    Identifier: 132,
    alphaCode: 'MDG',
    countryName: 'Madagascar',
    dialCode: '261',
  },
  {
    Identifier: 133,
    alphaCode: 'MWI',
    countryName: 'Malawi',
    dialCode: '265',
  },
  {
    Identifier: 134,
    alphaCode: 'MYS',
    countryName: 'Malaysia',
    dialCode: '60',
  },
  {
    Identifier: 135,
    alphaCode: 'MDV',
    countryName: 'Maldives',
    dialCode: '960',
  },
  {
    Identifier: 136,
    alphaCode: 'MLI',
    countryName: 'Mali',
    dialCode: '223',
  },
  {
    Identifier: 137,
    alphaCode: 'MLT',
    countryName: 'Malta',
    dialCode: '356',
  },
  {
    Identifier: 138,
    alphaCode: 'MHL',
    countryName: 'Marshall Islands (the)',
    dialCode: '692',
  },
  {
    Identifier: 139,
    alphaCode: 'MTQ',
    countryName: 'Martinique',
    dialCode: '596',
  },
  {
    Identifier: 140,
    alphaCode: 'MRT',
    countryName: 'Mauritania',
    dialCode: '222',
  },
  {
    Identifier: 141,
    alphaCode: 'MUS',
    countryName: 'Mauritius',
    dialCode: '230',
  },
  {
    Identifier: 142,
    alphaCode: 'MYT',
    countryName: 'Mayotte',
    dialCode: '262',
  },
  {
    Identifier: 143,
    alphaCode: 'MEX',
    countryName: 'Mexico',
    dialCode: '52',
  },
  {
    Identifier: 144,
    alphaCode: 'FSM',
    countryName: 'Micronesia (Federated States of)',
    dialCode: '691',
  },
  {
    Identifier: 179,
    alphaCode: 'MDA',
    countryName: 'Moldova (the Republic of)',
    dialCode: '373',
  },
  {
    Identifier: 145,
    alphaCode: 'MCO',
    countryName: 'Monaco',
    dialCode: '377',
  },
  {
    Identifier: 146,
    alphaCode: 'MNG',
    countryName: 'Mongolia',
    dialCode: '976',
  },
  {
    Identifier: 147,
    alphaCode: 'MNE',
    countryName: 'Montenegro',
    dialCode: '382',
  },
  {
    Identifier: 148,
    alphaCode: 'MSR',
    countryName: 'Montserrat',
    dialCode: '1-664',
  },
  {
    Identifier: 149,
    alphaCode: 'MAR',
    countryName: 'Morocco',
    dialCode: '212',
  },
  {
    Identifier: 150,
    alphaCode: 'MOZ',
    countryName: 'Mozambique',
    dialCode: '258',
  },
  {
    Identifier: 152,
    alphaCode: 'NAM',
    countryName: 'Namibia',
    dialCode: '264',
  },
  {
    Identifier: 153,
    alphaCode: 'NRU',
    countryName: 'Nauru',
    dialCode: '674',
  },
  {
    Identifier: 154,
    alphaCode: 'NPL',
    countryName: 'Nepal',
    dialCode: '977',
  },
  {
    Identifier: 155,
    alphaCode: 'NLD',
    countryName: 'Netherlands (Europe)',
    dialCode: '31',
  },
  {
    Identifier: 156,
    alphaCode: 'NCL',
    countryName: 'New Caledonia',
    dialCode: '687',
  },
  {
    Identifier: 157,
    alphaCode: 'NZL',
    countryName: 'New Zealand',
    dialCode: '64',
  },
  {
    Identifier: 158,
    alphaCode: 'NIC',
    countryName: 'Nicaragua',
    dialCode: '505',
  },
  {
    Identifier: 159,
    alphaCode: 'NER',
    countryName: 'Niger (the)',
    dialCode: '227',
  },
  {
    Identifier: 160,
    alphaCode: 'NGA',
    countryName: 'Nigeria',
    dialCode: '234',
  },
  {
    Identifier: 161,
    alphaCode: 'NIU',
    countryName: 'Niue',
    dialCode: '683',
  },
  {
    Identifier: 162,
    alphaCode: 'NFK',
    countryName: 'Norfolk Island',
    dialCode: '672',
  },
  {
    Identifier: 220,
    alphaCode: 'MKD',
    countryName: 'North Macedonia',
    dialCode: '389',
  },
  {
    Identifier: 163,
    alphaCode: 'MNP',
    countryName: 'Northern Mariana Islands (the)',
    dialCode: '1-670',
  },
  {
    Identifier: 164,
    alphaCode: 'NOR',
    countryName: 'Norway',
    dialCode: '47',
  },
  {
    Identifier: 165,
    alphaCode: 'OMN',
    countryName: 'Oman',
    dialCode: '968',
  },
  {
    Identifier: 166,
    alphaCode: 'PAK',
    countryName: 'Pakistan',
    dialCode: '92',
  },
  {
    Identifier: 167,
    alphaCode: 'PLW',
    countryName: 'Palau',
    dialCode: '680',
  },
  {
    Identifier: 210,
    alphaCode: 'PSE',
    countryName: 'Palestine, State of',
    dialCode: '970',
  },
  {
    Identifier: 168,
    alphaCode: 'PAN',
    countryName: 'Panama',
    dialCode: '507',
  },
  {
    Identifier: 169,
    alphaCode: 'PNG',
    countryName: 'Papua New Guinea',
    dialCode: '675',
  },
  {
    Identifier: 170,
    alphaCode: 'PRY',
    countryName: 'Paraguay',
    dialCode: '595',
  },
  {
    Identifier: 171,
    alphaCode: 'PER',
    countryName: 'Peru',
    dialCode: '51',
  },
  {
    Identifier: 172,
    alphaCode: 'PHL',
    countryName: 'Philippines (the)',
    dialCode: '63',
  },
  {
    Identifier: 173,
    alphaCode: 'PCN',
    countryName: 'Pitcairn',
    dialCode: '870',
  },
  {
    Identifier: 174,
    alphaCode: 'POL',
    countryName: 'Poland',
    dialCode: '48',
  },
  {
    Identifier: 175,
    alphaCode: 'PRT',
    countryName: 'Portugal',
    dialCode: '351',
  },
  {
    Identifier: 176,
    alphaCode: 'PRI',
    countryName: 'Puerto Rico',
    dialCode: '1',
  },
  {
    Identifier: 177,
    alphaCode: 'QAT',
    countryName: 'Qatar',
    dialCode: '974',
  },
  {
    Identifier: 183,
    alphaCode: 'REU',
    countryName: 'Reunion',
    dialCode: '262',
  },
  {
    Identifier: 180,
    alphaCode: 'ROU',
    countryName: 'Romania',
    dialCode: '40',
  },
  {
    Identifier: 181,
    alphaCode: 'RUS',
    countryName: 'Russian Federation (the)',
    dialCode: '7',
  },
  {
    Identifier: 182,
    alphaCode: 'RWA',
    countryName: 'Rwanda',
    dialCode: '250',
  },
  {
    Identifier: 184,
    alphaCode: 'BLM',
    countryName: 'Saint Barthelemy',
    dialCode: '590',
  },
  {
    Identifier: 185,
    alphaCode: 'SHN',
    countryName: 'Saint Helena, Ascension and Tristan da Cunha',
    dialCode: '290',
  },
  {
    Identifier: 186,
    alphaCode: 'KNA',
    countryName: 'Saint Kitts And Nevis',
    dialCode: '1-869',
  },
  {
    Identifier: 187,
    alphaCode: 'LCA',
    countryName: 'Saint Lucia',
    dialCode: '1-758',
  },
  {
    Identifier: 188,
    alphaCode: 'MAF',
    countryName: 'Saint Martin (French part)',
    dialCode: '590',
  },
  {
    Identifier: 189,
    alphaCode: 'SPM',
    countryName: 'Saint Pierre And Miquelon',
    dialCode: '508',
  },
  {
    Identifier: 190,
    alphaCode: 'VCT',
    countryName: 'Saint Vincent and the Grenadines',
    dialCode: '1-784',
  },
  {
    Identifier: 191,
    alphaCode: 'WSM',
    countryName: 'Samoa',
    dialCode: '685',
  },
  {
    Identifier: 192,
    alphaCode: 'SMR',
    countryName: 'San Marino',
    dialCode: '378',
  },
  {
    Identifier: 193,
    alphaCode: 'STP',
    countryName: 'Sao Tome And Principe',
    dialCode: '239',
  },
  {
    Identifier: 194,
    alphaCode: 'SAU',
    countryName: 'Saudi Arabia',
    dialCode: '966',
  },
  {
    Identifier: 195,
    alphaCode: 'SEN',
    countryName: 'Senegal',
    dialCode: '221',
  },
  {
    Identifier: 196,
    alphaCode: 'SRB',
    countryName: 'Serbia',
    dialCode: '381',
  },
  {
    Identifier: 197,
    alphaCode: 'SYC',
    countryName: 'Seychelles',
    dialCode: '248',
  },
  {
    Identifier: 198,
    alphaCode: 'SLE',
    countryName: 'Sierra Leone',
    dialCode: '232',
  },
  {
    Identifier: 199,
    alphaCode: 'SGP',
    countryName: 'Singapore',
    dialCode: '65',
  },
  {
    Identifier: 200,
    alphaCode: 'SXM',
    countryName: 'Sint Maarten (Dutch part)',
    dialCode: '1-721',
  },
  {
    Identifier: 201,
    alphaCode: 'SVK',
    countryName: 'Slovakia',
    dialCode: '421',
  },
  {
    Identifier: 202,
    alphaCode: 'SVN',
    countryName: 'Slovenia',
    dialCode: '386',
  },
  {
    Identifier: 203,
    alphaCode: 'SLB',
    countryName: 'Solomon Islands',
    dialCode: '677',
  },
  {
    Identifier: 204,
    alphaCode: 'SOM',
    countryName: 'Somalia',
    dialCode: '252',
  },
  {
    Identifier: 205,
    alphaCode: 'ZAF',
    countryName: 'South Africa',
    dialCode: '27',
  },
  {
    Identifier: 206,
    alphaCode: 'SGS',
    countryName: 'South Georgia and the South Sandwich Islands',
    dialCode: '500',
  },
  {
    Identifier: 207,
    alphaCode: 'SSD',
    countryName: 'South Sudan',
    dialCode: '211',
  },
  {
    Identifier: 208,
    alphaCode: 'ESP',
    countryName: 'Spain',
    dialCode: '34',
  },
  {
    Identifier: 209,
    alphaCode: 'LKA',
    countryName: 'Sri Lanka',
    dialCode: '94',
  },
  {
    Identifier: 211,
    alphaCode: 'SDN',
    countryName: 'Sudan (the)',
    dialCode: '249',
  },
  {
    Identifier: 212,
    alphaCode: 'SUR',
    countryName: 'Suriname',
    dialCode: '597',
  },
  {
    Identifier: 213,
    alphaCode: 'SJM',
    countryName: 'Svalbard and Jan Mayen',
    dialCode: '47',
  },
  {
    Identifier: 215,
    alphaCode: 'SWE',
    countryName: 'Sweden',
    dialCode: '46',
  },
  {
    Identifier: 216,
    alphaCode: 'CHE',
    countryName: 'Switzerland',
    dialCode: '41',
  },
  {
    Identifier: 217,
    alphaCode: 'SYR',
    countryName: 'Syrian Arab Republic (the)',
    dialCode: '963',
  },
  {
    Identifier: 1,
    alphaCode: 'TWN',
    countryName: 'Taiwan (Province of China)',
    dialCode: '886',
  },
  {
    Identifier: 218,
    alphaCode: 'TJK',
    countryName: 'Tajikistan',
    dialCode: '992',
  },
  {
    Identifier: 235,
    alphaCode: 'TZA',
    countryName: 'Tanzania, the United Republic of',
    dialCode: '255',
  },
  {
    Identifier: 219,
    alphaCode: 'THA',
    countryName: 'Thailand',
    dialCode: '66',
  },
  {
    Identifier: 222,
    alphaCode: 'TGO',
    countryName: 'Togo',
    dialCode: '228',
  },
  {
    Identifier: 223,
    alphaCode: 'TKL',
    countryName: 'Tokelau',
    dialCode: '690',
  },
  {
    Identifier: 224,
    alphaCode: 'TON',
    countryName: 'Tonga',
    dialCode: '676',
  },
  {
    Identifier: 225,
    alphaCode: 'TTO',
    countryName: 'Trinidad And Tobago',
    dialCode: '1-868',
  },
  {
    Identifier: 226,
    alphaCode: 'TUN',
    countryName: 'Tunisia',
    dialCode: '216',
  },
  {
    Identifier: 227,
    alphaCode: 'TUR',
    countryName: 'Turkey',
    dialCode: '90',
  },
  {
    Identifier: 252,
    alphaCode: 'XXT',
    countryName: 'Turkish Controlled Areas of Cyprus',
    dialCode: '90',
  },
  {
    Identifier: 228,
    alphaCode: 'TKM',
    countryName: 'Turkmenistan',
    dialCode: '993',
  },
  {
    Identifier: 229,
    alphaCode: 'TCA',
    countryName: 'Turks And Caicos Islands (the)',
    dialCode: '1-649',
  },
  {
    Identifier: 230,
    alphaCode: 'TUV',
    countryName: 'Tuvalu',
    dialCode: '688',
  },
  {
    Identifier: 231,
    alphaCode: 'UGA',
    countryName: 'Uganda',
    dialCode: '256',
  },
  {
    Identifier: 232,
    alphaCode: 'UKR',
    countryName: 'Ukraine',
    dialCode: '380',
  },
  {
    Identifier: 233,
    alphaCode: 'ARE',
    countryName: 'United Arab Emirates (the)',
    dialCode: '971',
  },
  {
    Identifier: 234,
    alphaCode: 'GBR',
    countryName: 'United Kingdom of Great Britain and Northern Ireland',
    dialCode: '44',
  },
  {
    Identifier: 236,
    alphaCode: 'UMI',
    countryName: 'United States Minor Outlying Islands (the)',
    dialCode: '246',
  },
  {
    Identifier: 238,
    alphaCode: 'USA',
    countryName: 'United States of America (the)',
    dialCode: '1',
  },
  {
    Identifier: 239,
    alphaCode: 'URY',
    countryName: 'Uruguay',
    dialCode: '598',
  },
  {
    Identifier: 240,
    alphaCode: 'UZB',
    countryName: 'Uzbekistan',
    dialCode: '998',
  },
  {
    Identifier: 241,
    alphaCode: 'VUT',
    countryName: 'Vanuatu',
    dialCode: '678',
  },
  {
    Identifier: 102,
    alphaCode: 'VAT',
    countryName: 'Vatican City',
    dialCode: '39-06',
  },
  {
    Identifier: 242,
    alphaCode: 'VEN',
    countryName: 'Venezuela (Bolivarian Republic of)',
    dialCode: '58',
  },
  {
    Identifier: 243,
    alphaCode: 'VNM',
    countryName: 'Vietnam',
    dialCode: '84',
  },
  {
    Identifier: 34,
    alphaCode: 'VGB',
    countryName: 'Virgin Islands (British)',
    dialCode: '1-284',
  },
  {
    Identifier: 237,
    alphaCode: 'VIR',
    countryName: 'Virgin Islands (U.S.)',
    dialCode: '1-340',
  },
  {
    Identifier: 244,
    alphaCode: 'WLF',
    countryName: 'Wallis And Futuna',
    dialCode: '681',
  },
  {
    Identifier: 245,
    alphaCode: 'ESH',
    countryName: 'Western Sahara',
    dialCode: '212',
  },
  {
    Identifier: 246,
    alphaCode: 'YEM',
    countryName: 'Yemen',
    dialCode: '967',
  },
  {
    Identifier: 247,
    alphaCode: 'ZMB',
    countryName: 'Zambia',
    dialCode: '260',
  },
  {
    Identifier: 248,
    alphaCode: 'ZWE',
    countryName: 'Zimbabwe',
    dialCode: '263',
  },
];
